### ISSUE TITLE
problemen notebooks

### ISSUE THREAD

**Issue by JolienVanGoethem** [claesenm/kul-systeemtheorie#10]
Ik ben de notebooks aan het uitproberen op mijn mac-computer, maar ik heb problemen sinds ik een nieuwe versie van matplotlib heb geïnstalleerd. Voor kwart na 11 kon ik alle notebooks uitvoeren, maar bij het notebook bode plot (met tkinter) gaf het userface geen figuren weer (+ het gaf een error betreffende style van matplotlib). Ik had toen een vorige versie van matplotlib dus heb ik mijn matplotlib geüpgrade, maar nu werkt er niets meer: het gaat fout bij het runnen van de imports aan het begin van elk notebook. Mijn terminal geeft wel weer dat de nieuwe versie van matplotlib is geïnstalleerd.

**Comment by claesenm** [comment]
Ik zal in de namiddag langskomen, waarschijnlijk rond 15:30, om te kijken
of we het kunnen oplossen.

Op 28 juli 2015 11:41 schreef JolienVanGoethem notifications@github.com:
