### ISSUE TITLE
Problemen met pushen

### ISSUE THREAD

**Issue by StevenColleman** [claesenm/kul-systeemtheorie#11]
Beste,

toen ik gisterenavond mijn werk van gisteren wilde pushen, lukte dit niet. Jolien en Menno zagen ook niet wat het probleem was. Zou iemand ons willen komen helpen? Dank bij voorbaat!

Groetjes,
Steven Colleman

**Comment by claesenm** [comment]
Ik kom ASAP langs, ik wordt momenteel gegijzeld door de NMBS dus we zullen
zien wanneer dat precies is.

Op 4 augustus 2015 09:12 schreef StevenColleman notifications@github.com:

**Comment by claesenm** [comment]
Heb ik jouw github account al toegevoegd? Indien niet, dan is dat de reden
dat je niet kan pushen. Wat is je github username?

Op 4 augustus 2015 09:14 schreef Marc Claesen claesenm@gmail.com:

**Comment by StevenColleman** [comment]
Beste,

mijn username is 'StevenColleman'.

**Comment by claesenm** [comment]
Ik heb je toegevoegd, moest het nu nog niet werken laat je maar iets weten.

**Comment by StevenColleman** [comment]
Beste,

ik heb vanavond geprobeerd om mijn werk van vandaag te pushen maar om de één of andere reden lukte het toch nog altijd niet. Zou u morgen eens willen komen kijken?

Groetjes,
Steven

**Comment by claesenm** [comment]
Ok, ik kom morgen in de voormiddaag langs.

Op 4 augustus 2015 18:00 schreef StevenColleman notifications@github.com:
