### ISSUE TITLE
Defining ipython functions

### ISSUE THREAD

**Issue by JonahVA** [claesenm/kul-systeemtheorie#8]
Als ik een functie wil definieren die enkele plots geeft van een eerste  orde system, en die dan in een volgende cel wil gebruiken krijg ik de melding: name 'first_order_sytem' is not defined. Waaraan ligt deze error?

**Comment by claesenm** [comment]
In welk bestand krijg je dit probleem?

**Comment by JonahVA** [comment]
Nevermind, ik heb de fout gevonden. Er was ergens een naam verkeerd gedefinieerd;
