### ISSUE TITLE
texstudio: non writable document

### ISSUE THREAD

**Issue by JolienVanGoethem** [claesenm/kul-systeemtheorie#9]
Ik kan de slides van hoofdstuk 5 (Chapter 5 - Continuous-time systems) niet compilen op mijn computer. De slides zijn gemaakt door Jonah en al eens aangepast door Ellen, maar ik kan er geen blijvende aanpassingen in maken in TeXstudio. Volgende error-melding verschijnt wanneer ik het bestand probeer te compilen: "You cannot compile the document in a non writable director." Er moeten nog enkele aanpassingen gemaakt worden maar ik heb blijkbaar enkel leesrechten voor dat document, hoe kan ik dit oplossen? Alvast bedankt!

**Comment by claesenm** [comment]
Ik heb de permissies aangepast, nu zou het moeten werken. Kan je een git pull doen en kijken of het probleem nu opgelost is?

**Comment by JolienVanGoethem** [comment]
ik heb een pull gedaan, maar het geeft nog steeds hetzelfde probleem (ook bij alle andere latex bestanden die ik niet zelf heb geupload)

**Comment by claesenm** [comment]
Raar. Kan je de permissies per directory aanpassen?

**Comment by JolienVanGoethem** [comment]
Oei, dat weet ik niet, ik heb geen ervaring met Git, hoe zou ik dat moeten doen?

**Comment by claesenm** [comment]
Ik denk niet dat het een git probleem is, maar een echt windows probleem (in de veronderstelling dat je windows gebruikt). Als je mac gebruikt kan je best het volgende proberen in terminal:

> chmod 777 naam_van_directory

En binnen de directory

> chmod 777 \*

**Comment by JolienVanGoethem** [comment]
Ik gebruik mac, ik heb in de terminal chmod 777 ingegeven, vervolgens de map geopend met cd en daarna chmod 777\* in gegeven, maar hetzelfde probleem duikt opnieuw op

**Comment by JolienVanGoethem** [comment]
Is het mogelijk dat ik even met mijn computer langskom?

**Comment by claesenm** [comment]
Ik ben onderweg!

**Comment by claesenm** [comment]
Kan jij het script dat ik heb gemaakt ook toevoegen op git?
